name: Run Tests
on: [push]
jobs:
  RunBatteryTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install pytest
        run: pip install pytest pytest-spec pytest-describe
      - name: Run pytest
        run: pytest --spec --color=yes test_battery.py

  RunBehaveTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify the Python version being used

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install behave behave-webdriver
          python3 -m pip install selenium==3.141.0
          python3 -m pip install --upgrade urllib3==1.26.16

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131
          install-chromedriver: true
          install-dependencies: true
          
          

      - name: Run behave
        env:
          PATH: /usr/local/bin:$PATH  # Ensure chromedriver is in the PATH
        run: |
          python3 -m behave features