name: Run Tests
on: [push]
jobs:
  RunBatteryTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install pytest
        run: pip install pytest pytest-spec pytest-describe
      - name: Run pytest
        run: pytest --spec --color=yes test_battery.py

  RunBehaveTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: pip install behave behave-webdriver
          
          

      - name: Run behave
        env:
          PATH: /usr/local/bin:$PATH  # Ensure chromedriver is in the PATH
        run: |
          python3 -m behave features